{{- $ingressConfig := lookup "config.openshift.io/v1" "Ingress" "" "cluster" }}
{{- $clusterDomain := $ingressConfig.spec.domain }}
apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  location: ApplicationMenu
  text: Keycloak
  href: https://sso.{{ $clusterDomain }}
  applicationMenu:
    section: Red Hat Applications
    imageURL: https://sso.{{ $clusterDomain }}/favicon.ico
