{{- $clusterDomain := .Values.clusterDomain }}
{{- if not $clusterDomain }}
{{- $ingressConfig := lookup "config.openshift.io/v1" "Ingress" "" "cluster" }}
{{- if and $ingressConfig $ingressConfig.spec }}
{{- $clusterDomain = $ingressConfig.spec.domain }}
{{- end }}
{{- end }}
apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  location: ApplicationMenu
  text: Keycloak
  href: https://keycloak.{{ $clusterDomain }}
  applicationMenu:
    section: Red Hat Applications
    imageURL: https://keycloak.{{ $clusterDomain }}/favicon.ico
