{{- $secretKey := printf "%s/keycloak" .Values.clusterName }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-db-secret
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: keycloak-db-secret
    template:
      engineVersion: v2
      data:
        username: keycloak
        password: "{{ "{{ .password }}" }}"
  data:
  - secretKey: password
    remoteRef:
      key: {{ $secretKey }}
      property: db-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-sysadmin-password
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: keycloak-sysadmin-password
  data:
  - secretKey: password
    remoteRef:
      key: {{ $secretKey }}
      property: sysadmin-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-ocp-client-secret
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: keycloak-ocp-client-secret
  data:
  - secretKey: client-secret
    remoteRef:
      key: {{ $secretKey }}
      property: ocp-client-secret
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-gitlab-client-secret
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: keycloak-gitlab-client-secret
  data:
  - secretKey: client-secret
    remoteRef:
      key: {{ $secretKey }}
      property: gitlab-client-secret
