{{- if .Values.github.mapper }}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: keycloak-github-org-mapper
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: ServerSideApply=false
spec:
  lookupPolicy:
    local: true
---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-github-org-mapper
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  workspaces:
    - name: source
  params:
    - name: git-url
      type: string
      default: {{ .Values.sourceRepo | default "https://github.com/hfenner/ansibleforge.git" }}
    - name: git-revision
      type: string
      default: {{ .Values.sourceRevision | default "main" }}
    - name: image
      type: string
      default: image-registry.openshift-image-registry.svc:5000/{{ .Values.namespace }}/keycloak-github-org-mapper:latest
  tasks:
    - name: git-clone
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
      workspaces:
        - name: output
          workspace: source
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
    - name: maven-build
      runAfter:
        - git-clone
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: maven
          - name: namespace
            value: openshift-pipelines
      workspaces:
        - name: source
          workspace: source
      params:
        - name: GOALS
          value:
            - -f
            - keycloak-extensions/github-org-mapper/pom.xml
            - clean
            - package
            - -DskipTests
    - name: build-image
      runAfter:
        - maven-build
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: buildah
          - name: namespace
            value: openshift-pipelines
      workspaces:
        - name: source
          workspace: source
      params:
        - name: IMAGE
          value: $(params.image)
        - name: DOCKERFILE
          value: keycloak-extensions/github-org-mapper/Containerfile
        - name: CONTEXT
          value: keycloak-extensions/github-org-mapper
{{- end }}
