{{- $clusterDomain := .Values.clusterDomain }}
{{- if not $clusterDomain }}
{{- $ingressConfig := lookup "config.openshift.io/v1" "Ingress" "" "cluster" }}
{{- if and $ingressConfig $ingressConfig.spec }}
{{- $clusterDomain = $ingressConfig.spec.domain }}
{{- end }}
{{- end }}
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  instances: 1
  db:
    vendor: postgres
    host: keycloak-postgresql
    usernameSecret:
      name: keycloak-db-secret
      key: username
    passwordSecret:
      name: keycloak-db-secret
      key: password
    database: keycloak
  hostname:
    hostname: keycloak.{{ $clusterDomain }}
  http:
    httpEnabled: true
  proxy:
    headers: forwarded
  {{- if .Values.github.org }}
  unsupported:
    podTemplate:
      spec:
        initContainers:
          - name: load-providers
            image: image-registry.openshift-image-registry.svc:5000/{{ .Values.namespace }}/keycloak-github-org-mapper:latest
            command:
              - cp
              - /opt/keycloak-providers/keycloak-github-org-mapper.jar
              - /providers/
            volumeMounts:
              - name: providers
                mountPath: /providers
        containers:
          - volumeMounts:
              - name: providers
                mountPath: /opt/keycloak/providers/keycloak-github-org-mapper.jar
                subPath: keycloak-github-org-mapper.jar
        volumes:
          - name: providers
            emptyDir: {}
  {{- end }}
