{{- if and .Values.github.broker .Values.github.mapper .Values.github.org }}
apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: master-realm
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  keycloakCRName: keycloak
  placeholders:
    GITHUB_CLIENT_ID:
      secret:
        name: github-app-credentials
        key: client-id
    GITHUB_CLIENT_SECRET:
      secret:
        name: github-app-credentials
        key: client-secret
  realm:
    realm: master
    enabled: true
    groups:
      - name: admins
        realmRoles:
          - admin
    identityProviders:
      - alias: github
        providerId: github
        enabled: true
        trustEmail: true
        storeToken: true
        firstBrokerLoginFlowAlias: first broker login
        config:
          clientId: ${GITHUB_CLIENT_ID}
          clientSecret: ${GITHUB_CLIENT_SECRET}
          defaultScope: "user:email read:org"
          syncMode: FORCE
    identityProviderMappers:
      - name: github-username
        identityProviderAlias: github
        identityProviderMapper: oidc-username-idp-mapper
        config:
          syncMode: INHERIT
          template: "${ALIAS}.${CLAIM.login}"
      - name: github-org-admins
        identityProviderAlias: github
        identityProviderMapper: github-org-to-group-mapper
        config:
          syncMode: FORCE
          github.org: {{ .Values.github.org }}
          {{- if .Values.github.team }}
          github.team: {{ .Values.github.team }}
          {{- end }}
          keycloak.group: admins
{{- end }}
