{{- $clusterDomain := .Values.clusterDomain }}
{{- if not $clusterDomain }}
{{- $ingressConfig := lookup "config.openshift.io/v1" "Ingress" "" "cluster" }}
{{- if and $ingressConfig $ingressConfig.spec }}
{{- $clusterDomain = $ingressConfig.spec.domain }}
{{- end }}
{{- end }}
apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: sso-realm
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: ServerSideApply=false
spec:
  keycloakCRName: keycloak
  placeholders:
    OCP_CLIENT_SECRET:
      secret:
        name: keycloak-ocp-client-secret
        key: client-secret
    SYSADMIN_PASSWORD:
      secret:
        name: keycloak-sysadmin-password
        key: password
    GITLAB_CLIENT_SECRET:
      secret:
        name: keycloak-gitlab-client-secret
        key: client-secret
    {{- if .Values.gitlab.broker }}
    GITLAB_BROKER_CLIENT_ID:
      secret:
        name: gitlab-broker-credentials
        key: clientId
    GITLAB_BROKER_CLIENT_SECRET:
      secret:
        name: gitlab-broker-credentials
        key: clientSecret
    {{- end }}
    {{- if .Values.github.broker }}
    GITHUB_CLIENT_ID:
      secret:
        name: github-app-credentials
        key: client-id
    GITHUB_CLIENT_SECRET:
      secret:
        name: github-app-credentials
        key: client-secret
    {{- end }}
  realm:
    realm: sso
    enabled: true
    users:
      - username: sysadmin
        enabled: true
        firstName: System
        lastName: Administrator
        email: sysadmin@example.com
        credentials:
          - type: password
            value: ${SYSADMIN_PASSWORD}
            temporary: false
    clients:
      - clientId: gitlab
        enabled: true
        protocol: openid-connect
        publicClient: false
        standardFlowEnabled: true
        directAccessGrantsEnabled: false
        secret: ${GITLAB_CLIENT_SECRET}
        redirectUris:
          - https://gitlab.{{ $clusterDomain }}/users/auth/openid_connect/callback
        webOrigins:
          - https://gitlab.{{ $clusterDomain }}
        defaultClientScopes:
          - openid
          - profile
          - email
        attributes:
          pkce.code.challenge.method: S256
        protocolMappers:
          - name: groups
            protocol: openid-connect
            protocolMapper: oidc-group-membership-mapper
            config:
              claim.name: groups
              full.path: "false"
              id.token.claim: "true"
              access.token.claim: "true"
              userinfo.token.claim: "true"
      - clientId: idp-4-ocp
        enabled: true
        protocol: openid-connect
        publicClient: false
        standardFlowEnabled: true
        directAccessGrantsEnabled: false
        secret: ${OCP_CLIENT_SECRET}
        redirectUris:
          - https://oauth-openshift.{{ $clusterDomain }}/*
        webOrigins:
          - https://oauth-openshift.{{ $clusterDomain }}
        defaultClientScopes:
          - openid
          - profile
          - email
        attributes: {}
        protocolMappers:
          - name: groups
            protocol: openid-connect
            protocolMapper: oidc-group-membership-mapper
            config:
              claim.name: groups
              full.path: "false"
              id.token.claim: "true"
              access.token.claim: "true"
              userinfo.token.claim: "true"
      {{- if and .Values.aws.saml .Values.aws.accountId }}
      - clientId: "urn:amazon:webservices"
        name: "Amazon Web Services"
        enabled: true
        protocol: saml
        publicClient: false
        frontchannelLogout: true
        standardFlowEnabled: true
        directAccessGrantsEnabled: false
        attributes:
          saml.authnstatement: "true"
          saml.server.signature: "true"
          saml.force.post.binding: "true"
          saml.multivalued.roles: "false"
          saml_assertion_consumer_url_post: "https://signin.aws.amazon.com/saml"
          saml_single_logout_service_url_redirect: "https://signin.aws.amazon.com/saml"
          saml_idp_initiated_sso_url_name: "urn:amazon:webservices"
          saml_idp_initiated_sso_relay_state: "https://console.aws.amazon.com"
          saml.signing.certificate: ""
        redirectUris:
          - "https://signin.aws.amazon.com/saml"
        defaultClientScopes: []
        protocolMappers:
          - name: Session Duration
            protocol: saml
            protocolMapper: saml-hardcode-attribute-mapper
            config:
              attribute.nameformat: Basic
              attribute.name: "https://aws.amazon.com/SAML/Attributes/SessionDuration"
              friendly.name: "Session Duration"
              attribute.value: "28800"
          - name: Session Name
            protocol: saml
            protocolMapper: saml-user-property-mapper
            config:
              attribute.nameformat: Basic
              attribute.name: "https://aws.amazon.com/SAML/Attributes/RoleSessionName"
              friendly.name: "Session Name"
              user.attribute: email
          - name: AWS Role
            protocol: saml
            protocolMapper: saml-hardcode-attribute-mapper
            config:
              attribute.nameformat: Basic
              attribute.name: "https://aws.amazon.com/SAML/Attributes/Role"
              friendly.name: "AWS Role"
              attribute.value: "arn:aws:iam::{{ .Values.aws.accountId }}:role/KeycloakAdminAccess,arn:aws:iam::{{ .Values.aws.accountId }}:saml-provider/keycloak-sso"
      {{- end }}
    groups:
      - name: admins
      {{- if and .Values.github.broker .Values.github.mapper .Values.github.org }}
      - name: org-members
      {{- end }}
    {{- if or .Values.gitlab.broker .Values.github.broker }}
    identityProviders:
      {{- if .Values.gitlab.broker }}
      - alias: gitlab
        providerId: oidc
        enabled: true
        trustEmail: true
        firstBrokerLoginFlowAlias: first broker login
        config:
          clientId: ${GITLAB_BROKER_CLIENT_ID}
          clientSecret: ${GITLAB_BROKER_CLIENT_SECRET}
          authorizationUrl: https://gitlab.{{ $clusterDomain }}/oauth/authorize
          tokenUrl: https://gitlab.{{ $clusterDomain }}/oauth/token
          userInfoUrl: https://gitlab.{{ $clusterDomain }}/oauth/userinfo
          issuer: https://gitlab.{{ $clusterDomain }}
          defaultScope: openid profile email
          syncMode: FORCE
          pkceEnabled: "true"
          pkceMethod: S256
      {{- end }}
      {{- if .Values.github.broker }}
      - alias: github
        providerId: github
        enabled: true
        trustEmail: true
        storeToken: true
        firstBrokerLoginFlowAlias: first broker login
        config:
          clientId: ${GITHUB_CLIENT_ID}
          clientSecret: ${GITHUB_CLIENT_SECRET}
          defaultScope: "user:email{{ if .Values.github.mapper }} read:org{{ end }}"
          syncMode: FORCE
      {{- end }}
    identityProviderMappers:
      {{- if .Values.gitlab.broker }}
      - name: gitlab-username
        identityProviderAlias: gitlab
        identityProviderMapper: oidc-username-idp-mapper
        config:
          syncMode: INHERIT
          template: "${ALIAS}.${CLAIM.preferred_username}"
      {{- end }}
      {{- if .Values.github.broker }}
      - name: github-username
        identityProviderAlias: github
        identityProviderMapper: oidc-username-idp-mapper
        config:
          syncMode: INHERIT
          template: "${ALIAS}.${CLAIM.login}"
      {{- if and .Values.github.mapper .Values.github.org }}
      - name: github-org-admins
        identityProviderAlias: github
        identityProviderMapper: github-org-to-group-mapper
        config:
          syncMode: FORCE
          github.org: {{ .Values.github.org }}
          {{- if .Values.github.team }}
          github.team: {{ .Values.github.team }}
          {{- end }}
          keycloak.group: admins
      - name: github-org-members
        identityProviderAlias: github
        identityProviderMapper: github-org-to-group-mapper
        config:
          syncMode: FORCE
          github.org: {{ .Values.github.org }}
          keycloak.group: org-members
      {{- end }}
      {{- end }}
    {{- end }}
