{{- if .Values.gitlab.scm }}
{{- $oauthSecret := lookup "v1" "Secret" "gitlab-system" "gitlab-devspaces-oauth" }}
{{- if and $oauthSecret $oauthSecret.data }}
{{- $gitlabHost := .Values.gitlab.host }}
{{- if not $gitlabHost }}
{{- $dns := lookup "config.openshift.io/v1" "DNS" "" "cluster" }}
{{- if $dns }}
{{- $gitlabHost = printf "gitlab.apps.%s" $dns.spec.baseDomain }}
{{- end }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-oauth-config
  namespace: openshift-devspaces
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: oauth-scm-configuration
  annotations:
    che.eclipse.org/oauth-scm-server: gitlab
    che.eclipse.org/scm-server-endpoint: https://{{ $gitlabHost }}
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
data:
  id: {{ index $oauthSecret.data "id" }}
  secret: {{ index $oauthSecret.data "secret" }}
{{- end }}
{{- end }}
