{{- $awsStore := lookup "external-secrets.io/v1beta1" "ClusterSecretStore" "" "aws-secrets-manager" }}
{{- if and $awsStore $awsStore.metadata }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: htpasswd-secret
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: htpasswd-secret
    template:
      engineVersion: v2
      data:
        htpasswd: "{{ `{{ .htpasswd }}` }}"
  data:
  - secretKey: htpasswd
    remoteRef:
      key: openshift
      property: htpasswd
{{- end }}
