{{- $ingressConfig := lookup "config.openshift.io/v1" "Ingress" "" "cluster" }}
{{- $clusterDomain := "" }}
{{- if and $ingressConfig $ingressConfig.spec }}
{{- $clusterDomain = $ingressConfig.spec.domain }}
{{- end }}
apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: vault
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  location: ApplicationMenu
  text: HashiCorp Vault
  href: https://vault-vault.{{ $clusterDomain }}
  applicationMenu:
    section: Red Hat Applications
    imageURL: https://vault-vault.{{ $clusterDomain }}/ui/favicon.ico
