apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-bootstrap
  namespace: {{ .Values.argocd.namespace }}
spec:
  project: {{ .Values.argocd.project }}
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    path: {{ .Values.bootstrapPath }}
    helm:
      valueFiles:
        - values.yaml
        {{- range .Values.valueFiles }}
        - {{ . }}
        {{- end }}
      parameters:
        {{- if .Values.clusterDomain }}
        - name: clusterDomain
          value: {{ .Values.clusterDomain | quote }}
        {{- end }}
        {{- if .Values.aws.efs.filesystemId }}
        - name: components.efs.helm.parameters[0].name
          value: efs.filesystemId
        - name: components.efs.helm.parameters[0].value
          value: {{ .Values.aws.efs.filesystemId | quote }}
        {{- end }}
        {{- if .Values.aws.ingressCerts.acmeEmail }}
        - name: components.ingress-certs.helm.parameters[0].name
          value: acme.email
        - name: components.ingress-certs.helm.parameters[0].value
          value: {{ .Values.aws.ingressCerts.acmeEmail | quote }}
        {{- end }}
        {{- if .Values.aws.ingressCerts.route53Region }}
        - name: components.ingress-certs.helm.parameters[1].name
          value: route53.region
        - name: components.ingress-certs.helm.parameters[1].value
          value: {{ .Values.aws.ingressCerts.route53Region | quote }}
        {{- end }}
        {{- if .Values.aws.ingressCerts.route53HostedZoneID }}
        - name: components.ingress-certs.helm.parameters[2].name
          value: route53.hostedZoneID
        - name: components.ingress-certs.helm.parameters[2].value
          value: {{ .Values.aws.ingressCerts.route53HostedZoneID | quote }}
        {{- end }}
  destination:
    server: {{ .Values.argocd.destination.server }}
  syncPolicy:
    {{- toYaml .Values.syncPolicy | nindent 4 }}
