apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: openshift-gitops
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  resourceHealthChecks:
    - group: ""
      kind: PersistentVolumeClaim
      check: |
        hs = {}
        if obj.status == nil or obj.status.phase == nil then
          hs.status = "Healthy"
          hs.message = "Waiting for first consumer"
        elseif obj.status.phase == "Pending" then
          hs.status = "Healthy"
          hs.message = "Waiting for first consumer"
        elseif obj.status.phase == "Bound" then
          hs.status = "Healthy"
        else
          hs.status = "Degraded"
          hs.message = "PVC is in " .. obj.status.phase .. " phase"
        end
        return hs
    - group: operators.coreos.com
      kind: Subscription
      check: |
        hs = {}
        if obj.status ~= nil then
          if obj.status.state == "AtLatestKnown" then
            hs.status = "Healthy"
            hs.message = obj.status.installedCSV or "At latest known"
          elseif obj.status.state == "UpgradePending" then
            hs.status = "Progressing"
            hs.message = "Upgrade pending"
          else
            hs.status = "Degraded"
            hs.message = obj.status.state or "Unknown state"
          end
        else
          hs.status = "Progressing"
          hs.message = "Waiting for status"
        end
        return hs
  rbac:
    policy: |
      g, admins, role:admin
    scopes: '[groups]'
  server:
    route:
      enabled: true
  resourceTrackingMethod: annotation
