apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rhsm-credentials
  namespace: aap
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: rhsm-credentials
  data:
  - secretKey: username
    remoteRef:
      key: rhsm/{{ .Values.clusterName }}
      property: username
  - secretKey: password
    remoteRef:
      key: rhsm/{{ .Values.clusterName }}
      property: password
