clusterDomain: ""
clusterName: ""
namespace: keycloak

# GitLab as identity broker in Keycloak SSO realm
gitlab:
  broker: false

# GitHub as identity broker in Keycloak SSO realm
github:
  broker: false
  # GitHub organization for admin group mapping (requires custom SPI)
  org: ""
