apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: cert-manager-dns01-route53
  namespace: openshift-cloud-credential-operator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  secretRef:
    name: cert-manager-dns01-route53
    namespace: cert-manager
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    statementEntries:
      - effect: Allow
        action:
          - route53:GetChange
          - route53:ChangeResourceRecordSets
          - route53:ListResourceRecordSets
        resource: "*"
      - effect: Allow
        action:
          - route53:ListHostedZonesByName
          - route53:ListHostedZones
        resource: "*"
