apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-test
  namespace: external-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: vault-test
  data:
  - secretKey: token
    remoteRef:
      key: github
      property: token
