{{- if .Values.htpasswd.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: htpasswd-secret
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.htpasswd.secretStore }}
    kind: ClusterSecretStore
  target:
    name: htpasswd-secret
    template:
      engineVersion: v2
      data:
        htpasswd: "{{ `{{ htpasswd "ocpsysadmin" .password }}` }}"
  data:
  - secretKey: password
    remoteRef:
      key: {{ .Values.htpasswd.remoteKey }}
      property: sysadmin-password
{{- end }}
