{{- if .Values.keycloak.login }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-oidc-secret
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: keycloak-oidc-secret
    template:
      engineVersion: v2
      data:
        clientSecret: "{{ `{{ .clientSecret }}` }}"
  data:
  - secretKey: clientSecret
    remoteRef:
      key: {{ .Values.clusterName }}/keycloak
      property: ocp-client-secret
{{- end }}
