repoURL: "https://github.com/hfenner/ansibleforge.git"
targetRevision: "main"
bootstrapPath: "ocp/gitops/bootstrap"

argocd:
  namespace: openshift-gitops
  project: default
  destination:
    server: https://kubernetes.default.svc

syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - ServerSideApply=true
