apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rhdh-postgresql
  namespace: rhdh
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: rhdh-postgresql
  data:
    - secretKey: password
      remoteRef:
        key: /rhdh/postgresql-password
    - secretKey: postgres-password
      remoteRef:
        key: /rhdh/postgresql-admin-password
