apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: openshift-aws-efs-csi-driver
  namespace: openshift-cloud-credential-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  secretRef:
    name: aws-efs-cloud-credentials
    namespace: openshift-cluster-csi-drivers
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    statementEntries:
      - effect: Allow
        action:
          - elasticfilesystem:DescribeAccessPoints
          - elasticfilesystem:CreateAccessPoint
          - elasticfilesystem:DeleteAccessPoint
          - elasticfilesystem:TagResource
          - elasticfilesystem:DescribeFileSystems
          - elasticfilesystem:DescribeMountTargets
          - ec2:DescribeAvailabilityZones
        resource: "*"
