apiVersion: v1
kind: ConfigMap
metadata:
  name: workspace-env
  namespace: {{ .Values.username }}-devspaces
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  VAULT_ADDR: {{ .Values.vaultAddr }}
